[build.env]
passthrough = [
    "PKG_CONFIG_ALLOW_CROSS",
    "V8_FROM_SOURCE", # when cross compiling for windows we need to build from source
    "RUST_BACKTRACE",
    "RUST_LOG",
    "NINJA",
    "GN"
]

[target.aarch64-unknown-linux-gnu]
image = "boop-gtk/aarch64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
image = "boop-gtk/x86_64-unknown-linux-gnu"

[target.x86_64-pc-windows-gnu]
image = "boop-gtk/x86_64-pc-windows-gnu"
