name: Release

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # release-linux-amd64:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #     with:
  #       submodules: 'recursive'
  #   - name: GTK development librarys
  #     run: sudo apt-get install -y libgtk-3-dev libgtksourceview-3.0-dev
  #   - name: build
  #     run: cargo build --release --all-features 
  
  # release-windows:
  #   runs-on: windows-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #     with:
  #       submodules: 'recursive'
  #   - uses: numworks/setup-msys2@v1
  #   - name: GTK development librarys
  #     run: msys2do pacman -S --noconfirm mingw-w64-x86_64-gtk3 mingw-w64-x86_64-gtksourceview3 mingw-w64-x86_64-gtksourceviewmm3
  #   - name: build
  #     run: cargo build --release --all-features
  
  # release-macosx:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #     with:
  #       submodules: 'recursive'
  #   - name: GTK development librarys
  #     run: brew install gtk+3 gtksourceview3
  #   - name: build
  #     run: cargo build --release --all-features 

  # release-snap:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #     with:
  #       submodules: 'recursive'
  #   - uses: snapcore/action-build@v1

  release-flatpak:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Flatpak
      run: sudo apt-get update && sudo apt-get install flatpak libcap-dev libsoup-gnome2.4-dev libostree-dev libjson-glib-dev libcurl4-gnutls-dev libelf-dev libdwarf-dev xsltproc
    - name: Flatpak remote
      run: sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
    - name: Flatpak SDK's
      run: sudo flatpak install -y flathub org.freedesktop.Platform//19.08 org.freedesktop.Sdk//19.08 org.freedesktop.Sdk.Extension.rust-stable//19.08
    - name: Flatpak builder
      run: wget https://github.com/flatpak/flatpak-builder/releases/download/1.0.10/flatpak-builder-1.0.10.tar.xz && tar -xvf flatpak-builder-1.0.10.tar.xz && cd flatpak-builder-1.0.10 && ./configure --disable-documentation && make && sudo make install
    - name: Python TOML
      run: sudo apt-get install python3-toml 
    - name: Generate sources
      run: bash flatpak/gen-sources.sh
    - name: Flatpak
      run: flatpak-builder build-dir flatpak/uk.co.mrbenshef.Boop-GTK.json