name: Release

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

env:
  CARGO_TERM_COLOR: always
  PKG_CONFIG_ALLOW_CROSS: 1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        - dpkg: arm64
          triple: arm-linux-gnueabi
          rust: aarch64-unknown-linux-gnu
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: dpkg
      env:
        DPKG: ${{ matrix.dpkg }}
      run: sudo dpkg --add-architecture $DPKG
    - name: gcc and gtk
      env:
        GCC: gcc-${{ matrix.triple }}
        DPKG: ${{ matrix.dpkg }}
      run: |
        sudo apt-get install -y $GCC
        sudo apt-get install -y libgtk-3-dev:$DPKG
        sudo apt-get install -y libgtksourceview-3.0-dev:$DPKG
        sudo apt-get install -y pkg-config:$DPKG
    - name: rustup
      env:
        RUST: ${{ matrix.rust }}
      run: sudo rustup target add $RUST
    - name: build
      env:
        PKG_CONFIG_PATH: /usr/lib/${{ matrix.triple }}/pkgconfig/
        CARGO_BUILD_TARGET: ${{ matrix.rust }}
        RUSTFLAGS: "-C linker=${{ matrix.triple }}-gcc"
      run: cargo build --release
  