name: Release

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release-linux-amd64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: GTK development librarys
      run: sudo apt-get install -y libgtk-3-dev libgtksourceview-3.0-dev
    - name: build
      run: cargo build --release --all-features 
  
  release-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: numworks/setup-msys2@v1
    - name: GTK development librarys
      run: msys2do pacman -S mingw-w64-x86_64-gtk3 mingw-w64-x86_64-gtksourceview3
    - name: build
      run: cargo build --release --all-features
  
  release-macosx:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: GTK development librarys
      run: brew install gtk+3 gtksourceview3
    - name: build
      run: cargo build --release --all-features 

  release-snap:
    steps:
    - uses: actions/checkout@v2
    - uses: snapcore/action-build@v1

  release-flatpack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Pull the Docker Image
      run: docker pull bilelmoussaoui/flatpak-github-actions:latest
    - name: Run Docker Image
      run: |
            docker run --cap-add SYS_ADMIN --cap-add NET_ADMIN --device /dev/fuse \
                 --security-opt apparmor:unconfined --security-opt seccomp=unconfined \
                --workdir /github/workspace \
                --rm -e INPUT_ARGS -e HOME -e GITHUB_REF -e GITHUB_SHA  \
                -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW  \
                -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME \
                -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS  \
                -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE \
                -v "/var/run/docker.sock":"/var/run/docker.sock" \
                -v "/home/runner/work/_temp/_github_home":"/github/home" \
                -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" \
                -v ${{ github.workspace }}:"/github/workspace" \
                --rm -i bilelmoussaoui/flatpak-github-actions:latest \
                    --manifest-path "flatpak/uk.co.mrbenshef.Boop-GTK.json" \
                    --app-id "uk.co.mrbenshef.Boop-GTK" \
                    --bundle "Boop-GTK.flatpak"