name: Release

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

env:
  CARGO_TERM_COLOR: always
  PKG_CONFIG_ALLOW_CROSS: 1

jobs:
  release-amd64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features
  release-aarch64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: docker/build-push-action@v1
      with:
        push: false
        repository: boop-gtk/aarch64-unknown-linux-gnu
        dockerfile: docker/aarch64-unknown-linux-gnu.Dockerfile
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-unknown-linux-gnu
        override: true
    - uses: actions-rs/cargo@v1
      with:
        cross: true
        command: build
        args: --target aarch64-unknown-linux-gnu --release --all-features
  release-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features
