name: Release

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

env:
  CARGO_TERM_COLOR: always
  PKG_CONFIG_ALLOW_CROSS: 1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - dpkg: arm64
            gcc: gcc-arm-linux-gnueabi
            rust: aarch64-unknown-linux-gnu
            rust_cap: AARCH64_UNKNOWN_LINUX_GNUEABI
            linker: arm-linux-gnueabi-gcc
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: dpkg
      run: sudo dpkg --add-architecture ${{ matrix.dpkg }}
    - name: gcc and gtk
      run: |
        sudo apt-get install -y ${{ matrix.gcc }}
        sudo apt-get install -y libgtk-3-dev:${{ matrix.dpkg }}
        sudo apt-get install -y libgtksourceview-3.0-dev:${{ matrix.dpkg }}
        sudo apt-get install -y pkg-config:${{ matrix.dpkg }}
    - name: rustup
      run: sudo rustup target add ${{ matrix.rust }}
    - name: build
      run: PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabi/pkgconfig/ CARGO_BUILD_TARGET=armv7-unkown-linux-gnueabi CARGO_TARGET_${{ matrix.rust_cap }}_LINKER=${{ matrix.linker }} cargo build --release
  